### ISSUE TITLE
Deprecation or transfer of ownership

### ISSUE THREAD

**Issue by eliperelman** [eliperelman/fn.js#23]
As I do not have the time to maintain fn.js as I should, I would like to propose two options. By the end of next month, I will decide which option to take depending on community outcry.

1. Deprecate fn.js in favor of Ramda. I've been using Ramda pretty regularly now and enjoy it. I would be content with deprecating and recommending it.

2. Transfer ownership to someone else who can commit more time to it.

Thoughts? I'd like to make my decision and take action prior to November 30, 2015.

**Comment by watsoncj** [comment]
Thanks for being such a good steward!

Ramda is an excellent option.

**Comment by CrossEye** [comment]
I just saw this, and am quite saddened.  I'm one of the Ramda creators, and have been glad to have company in the journey we've been taking toward FP JS.  There were interesting predecessors, of course, but I've felt as though I few libraries were more like peers, especially fn, wu, and FKit.  (I can't include lodash-fp; the author really doesn't seem serious about it.)  Of these, wu has a very different focus, and FKit stalled pretty quickly.  fn has always seemed the closest peer to Ramda.

I hope someone does step forward.  I believe in diversity, and in competition.  And although I've only played around with fn, I've always been impressed.

If nothing else, I want to say thank you to Eli for shepherding this project as far as he has.  I know the job can be frustrating.  I hope it's been at least as rewarding.  Thank you.

**Comment by eliperelman** [comment]
@CrossEye thanks for the kind words! I've read some of your past posts on the subject, and with fn I had gone the route of trying to keep things as pure as possible, which has been somewhat detrimental. I believe Ramda went the right route with this.

I would definitely like to keep the mantle going if someone can improve on it. Having proper tail calls in ES6 will improve the performance of fn so the purity route may not be a completely lost cause.

Unfortunately my other OSS stuff at work keeps me very busy so I don't have the time to evolve the library, but would be happy if someone could continue what I started. :disappointed:

**Comment by CrowdHailer** [comment]
@eliperelman I would be interested on taking on fn.js. I would like to upgrade it to use es6 modules as I have been building a similar function utility anyway as I use rollup as a build step. Otherwise I envisage it remaining much the same

**Comment by eliperelman** [comment]
@CrowdHailer great timing, as I was just thinking about closing this as of this morning. There's a couple ways we could do this:

1. Start a new organization and transfer the repo there.
2. Add you as an owner to this repo.
3. Transfer ownership to you.

I am fine with any recourse. Thank you for being open to progressing fn.js!

**Comment by CrowdHailer** [comment]
Glad i got in there. I had been ruminating on taking over for a little while.
I don't really mind any of the above. I think it is small enough that I don't really need an organisation. between the master branch and gh-pages i think we have all that is needed.
Probably favourite would be (3)

**Comment by eliperelman** [comment]
Great then, 3 it is. I'll move it momentarily. Obviously you know you'll have to do some work to re-point the website for yourself for the gh-pages. Thanks again!

**Comment by CrossEye** [comment]
Thank you @CrowdHailer!

I could not take this on myself, as I'm already too strongly committed to another FP JS library, one with similar goals but different means of achieving them.  I couldn't possibly do two.  But I really do want to see `fn` thrive and grow.  I'm very glad to see someone taking the reins.

I can't offer a huge commitment of time, but if you need some help, I'm more than willing to pitch in where I can.  Feel free to call on me if you like.

Best of luck!

**Comment by CrowdHailer** [comment]
Thanks @CrossEye 
I have just started an issue to collect a list of libraries that have some of the same functionality as fn js. What is the library you are working on?

**Comment by eliperelman** [comment]
Scott is a core contributor to Ramda.
